name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          push: true
          tags: olechochek/rksp-front:latest

  deploy:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: sudo docker remove -f front && sudo docker pull olechochek/rksp-front:latest && sudo docker run --name front -p8080:80 -d olechochek/rksp-front:latest
